### ISSUE TITLE
Issue with Asset objects being processed in _cleanEntry

### ISSUE THREAD

**Issue by michaelcd** [drublic/contentful-to-algolia#1]
:wave: I'm using `contentful-to-algolia` on a project and I had a question about [this commit](https://github.com/drublic/contentful-to-algolia/commit/b9ca69d8f29659f156d5af55fcd14a00a07015b8). In `_cleanEntry` on line 97 it will access `entry.sys.contentType`, but the array of entries being sent to this code includes objects representing assets, which do not include the `contentType` key. 

I'm just curious which API you're using to build this library. I ran into the above error with the Delivery API, and I know some of Contentful's APIs deliver data in different formats.

Thanks for making this library though, it's been a big help.

**Comment by drublic** [comment]
Hi Michael,

thanks for the report. Does this still happen with v2.1.2? I had a couple of issues with these lines and tried to fix it. 
Does this work for you?

Kindly,
Hans

**Comment by drublic** [comment]
I will close this issue now. If the problem remains, please ping me or open a new issue. Thank you!
