### ISSUE TITLE
Add support for more than 100 entries

### ISSUE THREAD

**Issue by cearls** [drublic/contentful-to-algolia#3]
I have a content type with over 1000 entries, but the library currently only processes 100 entries. This feature could be implemented using the skip and limit parameters. Thoughts?

**Comment by drublic** [comment]
@cearls That makes a lot of sense. Do you want to open a Pull Request for this? I would love to see a configuration option for this.

**Comment by drublic** [comment]
Was fixed by #4, thanks to @AdamPflug.
